ExchangeSettings:
  Exchange: "kraken"            # https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets
  ExchangeKey: ""
  ExchangeSecret: ""
  ExchangePassword: ""

BotSettings:
  BTC/USD:                      # Only one bot per market
    Side: "buy"                 # buy/sell
    MaxTrades: 10               # Max open trades at a time (integer)
    TradeValue: 10.5            # Trade value per trade (float)
    PercOpen: 1                 # 1 = 1%
    PercClose: 1                # 1 = 1%
    TakeProfitIn: "USD"         # BTC or USD for BTC/USD
    ResetNextTradePrice: 1      # 1 = 1 day
  DOT/USD:                      # Only one bot per market
    Side: "buy"                 # Only buy is supported at the moment
    MaxTrades: 10               # Max open trades at a time (integer)
    TradeValue: 20.50           # Trade value per trade (float)
    PercOpen: 2                 # 2 = 2%
    PercClose: 2.5              # 2.5 = 2.5%
    TakeProfitIn: "DOT"         # DOT or USD for DOT/USD
    ResetNextTradePrice: 2      # 2 = 2 days
  EWT/USD:                      # Only one bot per market
    Side: "buy"                 # Only buy is supported at the moment
    MaxTrades: 10               # Max open trades at a time (integer)
    TradeValue: 101.6           # Trade value per trade (float)
    PercOpen: 2.5               # 2.5 = 2.5%
    PercClose: 2.5              # 2.5 = 2.5%
    TakeProfitIn: "USD"         # EWT or USD for EWT/USD
    ResetNextTradePrice: 3      # 3 = 3 days
  LINK/USD:                     # Only one bot per market
    Side: "sell"                # Only buy is supported at the moment
    MaxTrades: 10               # Max open trades at a time (integer)
    TradeValue: 10.5            # Trade value per trade (float)
    PercOpen: 1.5               # 1.5 = 1.5%
    PercClose: 1.5              # 1.5 = 1.5%
    TakeProfitIn: "LINK"        # LINK or USD for LINK/USD
    ResetNextTradePrice: 4      # 4 = 4 days

MongoDbSettings:
  Host: "localhost"             # default: localhost
  Port: 27017                   # default: 27017

PushoverSettings:
  PushoverEnabled: "false"      # true/false
  PushoverUserKey: ""
  PushoverAppToken: ""

LoggingSettings:
  LogLevel: "INFO"              # default: INFO (CRITICAL / ERROR / WARNING / INFO / DEBUG)
