name: PR
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p0ntsnl/python-lint-plus@master
        with:
          python-root-list: "hodlv2"
          virtual-env: "python-lint-plus"
          use-black: true
          use-isort: true
          use-pylint: true
          use-yapf: false
          use-docformatter: false
          use-pycodestyle: false
          use-autopep8: false
          use-pydocstyle: false
          use-mypy: false
          use-flake8: false
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false
